name: CI/CD

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'


# this block is used to define common steps for all jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Check for the existence of requirements.txt and instructions.txt
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install flake8 pytest
          if [ ! -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ ! -f requirements.txt ]; then echo "Error: requirements.txt not found"; exit 1; fi
          if [ ! -f instructions.txt ]; then echo "Error: instructions.txt not found"; exit 1; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run unit test with pytest
        run: |
          python -m pytest
          

  static-code-analysis:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Run bandit
      run: |
          bandit -r main.py >> scan_results.txt
          cat scan_results.txt
          if grep -E 'High: [1-9]|Medium: [1-9]' scan_results.txt; then
              echo "High or Medium level issues found. Cancelling pipeline..."
              exit 1
          else
              echo "No High or Medium level issues found. Continuing pipeline..."
          fi
          
